### ISSUE TITLE
Dash detection when Google Meet is picked up

### ISSUE THREAD

**Issue by mintyleaf** [Kentakoong/MusicBar#11]
![image](https://user-images.githubusercontent.com/17470408/204494704-462f6344-3f41-4839-bb43-c67f153028ee.png)

Can't really investigate, but native music selector picking it correctly)

**Comment by Kentakoong** [comment]
I see. cuz it's picking all of the media, and meet does use the Now Playing thing. So I guess ill do a gate to pick up that thing first.

**Comment by mintyleaf** [comment]
> I see. cuz it's picking all of the media, and meet does use the Now Playing thing. So I guess ill do a gate to pick up that thing first.

I think it's not big deal to pick or not to pick it, the problem is that it treats it's artist as Meet - id and song as " " or something else emptyish like that which didn't handled properly by the dash checker

**Comment by Kentakoong** [comment]
I have 2 options right now, I've just done the Google Meet checker. But it's up to the UX that should it be ignored or shown as just Google Meet and code?

What do you think will be the best choice?

**Comment by mintyleaf** [comment]
> I have 2 options right now, I've just done the Google Meet checker. But it's up to the UX that should it be ignored or shown as just Google Meet and code?
> 
> What do you think will be the best choice?
> 
> *ps: checked with Teams and Zoom, and this ain't occurring. So it's a Google Meet and Browser showing Music playing like youtube and such.

I think we don't need to go to that complicated stuff
What is good about your music bar - it's really simple, by just using native api for that

Maybe in future can be done the feature, which allows to blacklist providers by app name (if it possible by api), or by some regex idk

**Comment by Kentakoong** [comment]
then it will be fixed in #15 with the option to tick soon? i guess
