### ISSUE TITLE
Issues with album art fetching

### ISSUE THREAD

**Issue by mintyleaf** [Kentakoong/MusicBar#14]
It appears to be really rare to actually fetch it

**Comment by mintyleaf** [comment]
![image](https://user-images.githubusercontent.com/17470408/204521204-deacf1a1-61d7-4efc-b3d2-7cdabb5bdd51.png)
it's kinda eats about 5-6% cpu constantly, and spamming to the logs this
seems like it's updating every progress bar of the track update =\

**Comment by Kentakoong** [comment]
yep. I see the problem since the Xcode Logs. I'll find a way to not log it out.

**Comment by Kentakoong** [comment]
I think performance is better on the last patch, please check it out. Feel free to open it if it doesn't get better.
