### ISSUE TITLE
something wrong with the check mark

### ISSUE THREAD

**Issue by mintyleaf** [Kentakoong/MusicBar#16]
![image](https://user-images.githubusercontent.com/17470408/204663167-9cf213b5-dab1-4edf-accd-359017dc2e84.png)

**Comment by mintyleaf** [comment]
![image](https://user-images.githubusercontent.com/17470408/204663387-03da760e-626c-45ac-8f4e-1cfdd79bb03c.png)
I have other menubar app - it's fine

I guess it's using a default ui component, but..

**Comment by Kentakoong** [comment]
Yep, cuz the icon is from SF Symbols and Catalina Doesn't Support it. I'll find a way to fix it then.

**Comment by mintyleaf** [comment]
> Yep, cuz the icon is from SF Symbols and Catalina Doesn't Support it. I'll find a way to fix it then.

catalina?
but I'm on a monterey)
I sure that I had normal icons on 0.1.2 build

**Comment by Kentakoong** [comment]
Fixed at 8b5b99a
