### ISSUE TITLE
Disable album art?

### ISSUE THREAD

**Issue by johnmiles27** [Kentakoong/MusicBar#24]
Is there some way to disable the album art from showing in the menu bar, so only the artist and track title appear? It'd be great to have an option in the dropdown menu to toggle this, but in the meantime maybe there's some tweak I could make to the installed files? I'm using the App Store version fyi

**Comment by johnmiles27** [comment]
i just feel like it's too small to really see much detail anyway and maybe it would look cleaner with just the track info

**Comment by Kentakoong** [comment]
I'll create an improvement for that in the next pre-release, thanks for the suggestion!
