### ISSUE TITLE
album art at the center

### ISSUE THREAD

**Issue by mintyleaf** [Kentakoong/MusicBar#7]
![image](https://user-images.githubusercontent.com/17470408/204112802-bd19c8c1-c53c-43a3-9c53-6117e36fcbc1.png)

using Monterey 12.6.1

**Comment by mintyleaf** [comment]
![image](https://user-images.githubusercontent.com/17470408/204246330-ea268179-c157-409a-8955-d66a9db4895c.png)
still the same, even with "Music not playing" variant

**Comment by mintyleaf** [comment]
and for some reason it didn't even receive album art

**Comment by Kentakoong** [comment]
@mintyleaf is this problem fixed too? or is it still occurring

**Comment by mintyleaf** [comment]
> @mintyleaf is this problem fixed too? or is it still occurring

still occurring, seems like you didn't merge that pr into the build
(I can't build it by myself)

**Comment by Kentakoong** [comment]
Oh okay, but can i just build the .app and you try for me?

**Comment by mintyleaf** [comment]
> Oh okay, but can i just build the .app and you try for me?

yup, ofc

**Comment by Kentakoong** [comment]
Sorry for the late reply, here you go!
[MusicBar.app.zip](https://github.com/Kentakoong/MusicBar/files/10110554/MusicBar.app.zip)
